### PR TITLE
Update the README to use OCaml 5.0

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by patricoferris** [comment]
Do you think we should also point people in the direction of the [alpha repository](https://github.com/kit-ty-kate/opam-alpha-repository) if we make this change (some common dependencies are there like `lwt`, `ppxlib` etc.)?

**Comment by talex5** [comment]
Why change this now? OCaml 5 isn't released yet.

**Comment by Sudha247** [comment]
Even though OCaml 5 isn't released, I'd rather people do their experiments on `5.0.0+trunk` than on `4.12.0+domains`. `trunk` has progressed quite a lot from `4.12.0+domains`, and `4.12.0*` multicore variants are no longer actively maintained. Using trunk would:
* Prevent people running into bugs that were already fixed upstream.
* Ensure their application works with OCaml 5 when it's released. `trunk` has a lot of deprecated functions removed and quite a few changes in the C API which can be caught sooner than later.

**Comment by samoht** [comment]
Ha yes that's a good idea to advertise for opam-alpha-repository too (otherwise the experience might be quite poor :p)

**Comment by samoht** [comment]
> Why change this now? OCaml 5 isn't released yet.

As @Sudha247 said, I think it's a good idea to start preparing for OCaml 5. The compiler has entered in a phase of stabilisation and it'd be super helpful to make sure the ecosystem is ready for the release sooner than later :-)

**Comment by talex5** [comment]
We can update when the 5.0-alpha1 is released. Until then, the compiler is a moving target. It's hard enough to learn a new IO system, without being expected to debug a pre-alpha compiler at the same time.

As it says at https://diataxis.fr/tutorials/:

> One of your jobs as a tutor is to inspire the beginner’s confidence. Confidence can only be built up layer by layer, but is easily shaken. It helps to maintain a friendly tone, as does consistent use of language, and a logical progression through the material. However, the single most important requirement is that **what you ask the beginner to do must work**.

**Comment by samoht** [comment]
Well, the instruction is actually failing on macOS / arm64 with:
```
#=== ERROR while compiling ocaml-variants.4.12.0+domains ======================#
# context     2.1.2 | macos/arm64 |  | git+https://github.com/ocaml-multicore/multicore-opam.git
# path        ~/.opam/4.12.0+domains/.opam-switch/build/ocaml-variants.4.12.0+domains
# command     ~/.opam/opam-init/hooks/sandbox.sh build make -j9
# exit-code   2
# env-file    ~/.opam/log/ocaml-variants-168-d0d79a.env
# output-file ~/.opam/log/ocaml-variants-168-d0d79a.out
### output ###
# [...]
# cc -c -O2 -fno-strict-aliasing -fwrapv -Wall -Wdeclaration-after-statement -fno-common -g  -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE   -DCAMLDLLIMPORT= -DNATIVE_CODE -DTARGET_arm64 -DMODEL_default -DSYS_macosx   -o clambda_checks.n.o clambda_checks.c
# cc -c -O2 -fno-strict-aliasing -fwrapv -Wall -Wdeclaration-after-statement -fno-common -g  -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE   -DCAMLDLLIMPORT= -DNATIVE_CODE -DTARGET_arm64 -DMODEL_default -DSYS_macosx   -o afl.n.o afl.c
# cc -c -O2 -fno-strict-aliasing -fwrapv -Wall -Wdeclaration-after-statement -fno-common -g  -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE   -DCAMLDLLIMPORT= -DNATIVE_CODE -DTARGET_arm64 -DMODEL_default -DSYS_macosx   -o bigarray.n.o bigarray.c
# fiber.c:233:53: error: use of undeclared identifier 'Wosize_gc_regs'
#     value* bucket = caml_stat_alloc(sizeof(value) * Wosize_gc_regs);
#                                                     ^
# 1 error generated.
# make[3]: *** [fiber.n.o] Error 1
# make[3]: *** Waiting for unfinished jobs....
# make[2]: *** [makeruntimeopt] Error 2
# make[1]: *** [opt.opt] Error 2
# make: *** [world.opt] Error 2
```
while the 5.00 branch works fine. That's why I was trying to update the instruction to fix the install issues for "beginners" (who just hit the issue) :-)

**Comment by talex5** [comment]
This is a better reason :-) Maybe just include both options, and mention 5.0 is experimental, but needed for arm64?

**Comment by talex5** [comment]
I merged a version of this in #217 that suggests using trunk for ARM.

**Pull request closed without merging**
