### PR TITLE
Fix pipe hang (issue #319)

### PR DESCRIPTION
**Pull request by haesbaert**
Turns out the kernel needs to handle blocking file descriptors differently, it needs to do thread-pooling and it's a different code path (also slower).

It also seems that this is bugged in some cases. This makes sense as I believe most people don't test with blocking FDs. I believe we should make all our FDs non blocking as a precaution.

There is a program listed in issue #319 that replicates this. I could hang it in < 5 seconds, and it's now running for 10minutes with the fix, so kaboom.

### CODE REVIEW

**Comment by haesbaert** [comment]
There is a second hang in the `direct_copy` test, that is unrelated and I'm gonna have a look at it. I had it sporadically already and assumed would go away once this was fixed.

**Comment by haesbaert** [comment]
> There is a second hang in the `direct_copy` test, I'm not sure it is related now, but I could reproduce it before as well, this fixes the first one at least.

It's also likely I'm just hiding the original bug by changing some timing.

**Comment by talex5** [comment]
Is there an upstream bug report for this somewhere (e.g. on https://github.com/axboe/liburing)?

**Comment by haesbaert** [comment]
> Is there an upstream bug report for this somewhere (e.g. on https://github.com/axboe/liburing)?

I have to check deeper, I found a bunch of stuff related to bugs with pipes, also the commit for adding splice support for nonblocking in pipes is from June this year, it's all very recent (https://lore.kernel.org/all/20220607080619.513187-5-hao.xu@linux.dev/)

Basically setting the pipes to nonblocking fix the first case, but the second case makes the splice call return EAGAIN, and restarting/handling is not enough. it ends up hanging at some point.

I need to isolate things better before opening something upstream, but it all seems a bit dicey and immature, I'm writing C equivalents to make sure we're not missing something.

**Comment by haesbaert** [comment]
> 

As noted in https://github.com/ocaml-multicore/eio/issues/319#issuecomment-1258087688, I can reproduce the behaviour in that C program.

**Comment by anmonteiro** [comment]
> I believe we should make all our FDs non blocking as a precaution.

After reading through this PR and comments, I did this for my application, which solved hangs I was seeing under `eio_linux` for [eio-ssl](https://github.com/anmonteiro/eio-ssl)

**Comment by bikallem** [comment]
Probably outside of the scope of this PR, but shouldn't we make the sockets non blocking by default too - if they are not already? I was under the impression that the uring and luv backends both set sockets fd to be non-blocking by default. Is this not the case?

**Comment by haesbaert** [comment]
I've ran some more tests today and this is where we are:
 - The fix has been commited to mainline linux: https://github.com/torvalds/linux/commit/46a525e199e4037516f7e498c18f065b09df32ac
 - We can't expect users to be on kernel 6.1.
 - The fix we can do now is use pipes as non-blocking _and_ disable splice, I couldn't reproduce the bug with this.
 - The kernel fix also fixes the splice case, so it's the same bug, so in the future we can use it.
 - There are more things that need to be changed in uring but I wouldn't address that now, for now I'm concerned with just providing something that won't hang.

**Review by talex5 — APPROVED** [review]
I rebased it on `main` to fix the CI error.

**Comment by haesbaert** [comment]
> Is this ready to merge, or does it need splice to be disabled first?

Apologies, I should have been more clear, it's not ready, it was more like checking if this would be ok. I've also wanted to hunt the kernel versions where the patch has been applied and maybe test conditionally for disabling it, but I didn't get to it.

**Comment by haesbaert** [comment]
This should be good to go, I updated the commit message as well.

**Pull request merged**
