### PR TITLE
Relax return types of Eio.Process.pipe

### PR DESCRIPTION
**Pull request by Arogbonlo**
This updates the `pipe` function in the `Make_mgr` module to use polymorphic variants for its return types. The change allows the returned source and sink to be compatible with APIs expecting monomorphic types.
**Change:**
- Modified `pipe` function signature in `Make_mgr`
- Updated from `[...]` to `[>...]` for both source and sink types

This addresses issue #750, improving flexibility when working with various APIs that use stricter type definitions for sources and sinks.
- Added new test case demonstrating compatibility with constrained types

### CODE REVIEW

**Comment by patricoferris** [comment]
Hey @Arogbonlo,

Thanks for the PR. There are a few issues here that need addressed:

 - The original issue was to make the return type of `pipe` allow for _all possible subtypes_ (`<`) not to have _at least_ the variants it describes (`>`).
 - This is a type change and doesn't really require a test.

I think perhaps you should start again updating the types in `lib_eio/process.{ml.mli}` and following this through to `eio_unix`. I think you are also going to need to update the `Pipe` effect in `lib_eio/unix/private.ml` too. No other parts of the types should be changed (e.g. you changed `_ mgr` to  `'a t`)

**Comment by Arogbonlo** [comment]
I'll effect them immediately. Thank you.
@patricoferris

**Comment by patricoferris** [comment]
Hey @Arogbonlo how's it going? Do you need any help?

**Comment by Arogbonlo** [comment]
> Hey @Arogbonlo how's it going? Do you need any help?

Thank you so much for the check!

I'll push my progress in a few hours, so you can check it and let me know where i have to make changes.

**Comment by Arogbonlo** [comment]
Hey @patricoferris 

I just made a commit, please I'll appreciate your feedback on it.

Thank you.

**Review by patricoferris — CHANGES_REQUESTED** [review]
The changes are not building, see the [CI pipeline](https://github.com/ocaml-multicore/eio/pull/767/checks?check_run_id=31644899324).

Did you try running this locally? Also, it is good practice to use good commit messages instead of ".". If you need to redo something, you can always `git reset` and `git push -f` to your own branch.

**Pull request closed without merging**
